doctrine:
    dbal:
        url: "sqlite:///%kernel.project_dir%/var/data.db"
        driver: "pdo_sqlite"
        charset: utf8mb4
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true
